version: '3.8'

services:
  benchmark:
    build:
      context: .
      dockerfile: Dockerfile
    image: eberil/relink-benchmark:latest
    ports:
      - "8001:8001"
    environment:
      - SERVICE_NAME=benchmark
      - SERVICE_PORT=8001
      - DATABASE_URL=postgresql+asyncpg://seo_user:seo_pass@db:5432/seo_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - redis
      - db
      - ollama
    networks:
      - relink-network

networks:
  relink-network:
    external: true
