# 🚀 РЕВОЛЮЦИОННАЯ АРХИТЕКТУРА МИКРОСЕРВИСОВ reLink
# RAG-ориентированная архитектура с ChromaDB как основной БД

# Определение архитектуры для условной сборки
x-architecture: &architecture
  # Для Apple Silicon (ARM64)
  arm64: &arm64-config
    dockerfile: Dockerfile.apple-silicon
    platform: linux/arm64
  # Для x86_64
  amd64: &amd64-config
    dockerfile: Dockerfile.base
    platform: linux/amd64

services:
  # 🐳 БАЗОВЫЕ СЕРВИСЫ
  redis:
    image: redis:7-alpine
    container_name: relink-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    environment:
      - REDIS_PASSWORD=relink_redis_pass
    networks:
      - relink-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 🧠 AI/ML СЕРВИСЫ
  ollama:
    image: ollama/ollama:latest
    container_name: relink-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - relink-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 🗄️ ChromaDB - основная база данных
  chromadb:
    image: chromadb/chroma:latest
    container_name: relink-chromadb
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
      - ANONYMIZED_TELEMETRY=False
    networks:
      - relink-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 🔄 МИКРОСЕРВИСЫ (унифицированные на базе Dockerfile.base)
  router:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SERVICE_NAME: router
        SERVICE_PORT: 8001
    container_name: relink-router
    ports:
      - "8001:8001"
    environment:
      - SERVICE_NAME=router
      - SERVICE_PORT=8001
      - DEBUG=true
    networks:
      - relink-network
    depends_on:
      - ollama
      - chromadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  benchmark:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SERVICE_NAME: benchmark
        SERVICE_PORT: 8002
    container_name: relink-benchmark
    ports:
      - "8002:8002"
    environment:
      - SERVICE_NAME=benchmark
      - SERVICE_PORT=8002
      - DEBUG=true
    networks:
      - relink-network
    depends_on:
      - ollama
      - chromadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  relink:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SERVICE_NAME: relink
        SERVICE_PORT: 8003
    container_name: relink-service
    ports:
      - "8003:8003"
    environment:
      - SERVICE_NAME=relink
      - SERVICE_PORT=8003
      - DEBUG=true
    networks:
      - relink-network
    depends_on:
      - ollama
      - chromadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SERVICE_NAME: backend
        SERVICE_PORT: 8004
    container_name: relink-backend
    ports:
      - "8004:8004"
    environment:
      - SERVICE_NAME=backend
      - SERVICE_PORT=8004
      - DEBUG=true
    networks:
      - relink-network
    depends_on:
      - ollama
      - chromadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  llm_tuning:
    build:
      context: ./llm_tuning
      dockerfile: ${DOCKERFILE:-Dockerfile.apple-silicon}
      args:
        SERVICE_NAME: llm_tuning
        SERVICE_PORT: 8005
    container_name: relink-llm-tuning
    ports:
      - "8005:8005"
    environment:
      - SERVICE_NAME=llm_tuning
      - SERVICE_PORT=8005
      - DEBUG=true
    networks:
      - relink-network
    depends_on:
      - ollama
      - chromadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 🌐 Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: relink-frontend
    ports:
      - "3000:3000"
    networks:
      - relink-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 📊 Мониторинг
  monitoring:
    build:
      context: ./monitoring
      dockerfile: Dockerfile
    container_name: relink-monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - relink-network
    depends_on:
      - router
      - benchmark
      - relink
      - backend
      - llm_tuning
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 🧪 Тестирование
  testing:
    build:
      context: ./testing
      dockerfile: Dockerfile
    container_name: relink-testing
    networks:
      - relink-network
    depends_on:
      - router
      - benchmark
      - relink
      - backend
      - llm_tuning
      - frontend
    environment:
      - SELENIUM_HUB_URL=http://selenium-hub:4444
      - TEST_ENVIRONMENT=docker
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://backend:8004/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

# 🌐 Сети
networks:
  relink-network:
    driver: bridge

# 💾 Тома для персистентности данных
volumes:
  redis_data:
  ollama_data:
  chromadb_data: 