name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install black flake8 isort
          pip install -r seo-link-recommender/backend/requirements.txt
      - name: Lint
        run: |
          black --check seo-link-recommender/backend
          isort --check seo-link-recommender/backend
          flake8 seo-link-recommender/backend
      - name: Test
        run: |
          pytest seo-link-recommender/backend/tests --cov=seo-link-recommender/backend/app
