services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+asyncpg://seo_user:seo_pass@db:5432/seo_db
      - OLLAMA_URL=http://ollama:11434/api/generate
      - OLLAMA_MODEL=qwen2.5:7b-turbo
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v1/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - db
      - ollama

  docs:
    build:
      context: .
      dockerfile: docs/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CACHE_TTL=3600
      - CACHE_PREFIX=docs:
      - DOCS_PATH=/app/static
      - VERSION_FILE=/app/VERSION
      - README_FILE=/app/README.md
      - CORS_ORIGINS=["http://localhost:3000","http://frontend:80"]
    volumes:
      - ./VERSION:/app/VERSION:ro
      - ./README.md:/app/README.md:ro
      - ./TECHNICAL_ROADMAP.md:/app/static/TECHNICAL_ROADMAP.md:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8001/api/v1/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - redis

  monitoring:
    build:
      context: .
      dockerfile: monitoring/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+asyncpg://seo_user:seo_pass@db:5432/seo_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - OLLAMA_URL=http://ollama:11434
      - CACHE_TTL=3600
      - CACHE_PREFIX=monitoring:
      - COLLECT_INTERVAL=30
      - RETENTION_DAYS=30
      - CORS_ORIGINS=["http://localhost:3000","http://frontend:80"]
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8002/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - redis
      - db
      - ollama

  testing:
    build:
      context: .
      dockerfile: testing/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+asyncpg://seo_user:seo_pass@db:5432/seo_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=1
      - CACHE_TTL=3600
      - CACHE_PREFIX=testing:
      - CORS_ORIGINS=["http://localhost:3000","http://frontend:80"]
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
      - MAX_CONCURRENT_TESTS=10
      - TEST_TIMEOUT=300
      - REPORT_RETENTION_DAYS=30
      - METRICS_ENABLED=true
      - PROMETHEUS_PORT=9090
      - JAEGER_HOST=jaeger
      - JAEGER_PORT=6831
    volumes:
      - ./testing/reports:/app/reports
      - ./testing/test_data:/app/test_data
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8003/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - redis
      - db
      - prometheus
      - jaeger

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
      - docs
      - monitoring
      - testing

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: seo_user
      POSTGRES_PASSWORD: seo_pass
      POSTGRES_DB: seo_db
    volumes:
      - ../relink_db:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_models:/root/.ollama
      - ./scripts:/scripts
    environment:
      # 🚀 ОПТИМИЗАЦИЯ ДЛЯ APPLE M4
      - OLLAMA_KEEP_ALIVE=2h
      - OLLAMA_REQUEST_TIMEOUT=300s
      - OLLAMA_MAX_LOADED_MODELS=2
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_QUEUE=4
      - OLLAMA_CONCURRENT_REQUESTS=2
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=*
      - OLLAMA_LOAD_TIMEOUT=120s
      - OLLAMA_RUNNER_TIMEOUT=300s
      - OLLAMA_MODELS=/root/.ollama/models
      - OLLAMA_DEBUG=0
      
      # 🎯 ОПТИМИЗАЦИЯ КОНТЕКСТА И БАТЧИНГА
      - OLLAMA_MAX_TOKENS=4096
      - OLLAMA_CONTEXT_LENGTH=4096
      - OLLAMA_BATCH_SIZE=512
      - OLLAMA_TEMPERATURE=0.7
      - OLLAMA_TOP_P=0.9
      - OLLAMA_REPEAT_PENALTY=1.1
      - OLLAMA_SEED=42
      
      # 🔥 МАКСИМАЛЬНАЯ ПРОИЗВОДИТЕЛЬНОСТЬ ДЛЯ APPLE M4 КОНТЕЙНЕР
      - OLLAMA_FLASH_ATTENTION=1        # CPU Flash Attention оптимизация
      - OLLAMA_KV_CACHE_TYPE=q8_0       # Квантованный кэш для экономии памяти
      - OLLAMA_COMPUTE_UNIT_LIMIT=0     # Без ограничений вычислительных единиц
      - OLLAMA_CPU_OPTIMIZATION=1       # Включаем CPU оптимизации
      - OLLAMA_SIMD_ACCELERATION=1      # SIMD ускорение для ARM64
      - OLLAMA_NEON_OPTIMIZATION=1      # ARM NEON оптимизации
      
      # ⚡ CPU ТУРБО-РЕЖИМ для Apple Silicon
      - OLLAMA_THREADS=8                # Максимум потоков для M4
      - OLLAMA_CPU_AFFINITY=0-7         # Привязка к Performance ядрам
      - OLLAMA_PREFER_CPU=true          # Принудительное использование CPU
      - OLLAMA_ARM64_OPTIMIZED=1        # ARM64 специфичные оптимизации
      
      # 🧠 ОПТИМИЗАЦИЯ ПАМЯТИ для M4
      - OLLAMA_LOW_MEM=false            # Не экономим память - у M4 её достаточно
      - OLLAMA_MEM_FRACTION=0.85        # 85% памяти контейнера для модели
      - OLLAMA_MMAP_ENABLED=1           # Memory mapping для быстрого доступа
      - OLLAMA_HUGE_PAGES=1             # Используем большие страницы памяти
      
      - OLLAMA_PRELOAD_MODEL=qwen2.5:7b-turbo
      - OLLAMA_WORKERS=2
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "ollama serve & 
      sleep 45 && 
      echo '🚀 Загружаем модели для A/B тестирования...' && 
      ollama pull qwen2.5:7b && 
      ollama pull qwen2.5:7b-instruct && 
      
      echo '⚡ Создаем ТУРБО модель (базовая)...' && 
      ollama create qwen2.5:7b-turbo -f /dev/stdin <<EOF
      FROM qwen2.5:7b
      # 🔥 ТУРБО параметры для Apple M4 CPU
      PARAMETER num_ctx 4096
      PARAMETER num_batch 512
      PARAMETER num_thread 8
      PARAMETER num_gpu 0
      PARAMETER f16_kv true
      PARAMETER use_mmap true
      PARAMETER use_mlock true
      PARAMETER num_predict 2048
      PARAMETER temperature 0.7
      PARAMETER top_p 0.9
      PARAMETER repeat_penalty 1.1
      PARAMETER seed 42
      EOF
      
      echo '🎯 Создаем INSTRUCT ТУРБО модель...' && 
      ollama create qwen2.5:7b-instruct-turbo -f /dev/stdin <<EOF
      FROM qwen2.5:7b-instruct
      # 🎯 INSTRUCT ТУРБО для SEO задач M4 CPU
      PARAMETER num_ctx 4096
      PARAMETER num_batch 512
      PARAMETER num_thread 8
      PARAMETER num_gpu 0
      PARAMETER f16_kv true
      PARAMETER use_mmap true
      PARAMETER use_mlock true
      PARAMETER num_predict 2048
      PARAMETER temperature 0.6
      PARAMETER top_p 0.85
      PARAMETER repeat_penalty 1.05
      PARAMETER seed 42
      # Специально для инструкций
      PARAMETER stop \"<|im_end|>\"
      PARAMETER stop \"<|endoftext|>\"
      EOF
      
      echo '🏆 Обе модели готовы для бенчмарка!' &&
      echo '⚡ Предпрогреваем систему...' &&
      ollama run qwen2.5:7b-turbo 'Система готова для бенчмарка!' &&
      ollama run qwen2.5:7b-instruct-turbo 'Instruct модель готова!' &&
      echo '🔥 Apple M4 A/B система активирована!' &&
      wait"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:11434/api/tags"]
      interval: 60s
      timeout: 45s
      retries: 5
      start_period: 600s
    deploy:
      resources:
        limits:
          memory: 16G
          cpus: '8.0'
        reservations:
          memory: 8G
          cpus: '4.0'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    security_opt:
      - seccomp:unconfined
    ipc: host

  # 🚀 МОНИТОРИНГ И ОБСЕРВАБИЛЬНОСТЬ
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - prometheus
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "6832:6832/udp"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:16686/api/services"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # 📊 ДОПОЛНИТЕЛЬНЫЕ СЕРВИСЫ ДЛЯ ТЕСТИРОВАНИЯ
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - docs
      - monitoring
      - testing
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8082:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@relink.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8080:8080"
    volumes:
      - ./testing/wiremock:/home/wiremock
    command: --verbose
    restart: unless-stopped

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  elasticsearch_data:
    driver: local
  minio_data:
    driver: local
  pgadmin_data:
    driver: local
