name: CI

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f seo_link_recommender/backend/requirements.txt ]; then pip install -r seo_link_recommender/backend/requirements.txt; fi
      - name: Run tests
        run: python -m pytest -q
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        env:
          REGISTRY_TOKEN: ${{ secrets.GHCR_TOKEN || secrets.GITHUB_TOKEN }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ env.REGISTRY_TOKEN }}
      - name: Build and push latest
        uses: docker/build-push-action@v5
        with:
          context: ./seo_link_recommender/backend
          file: ./seo_link_recommender/backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
      - name: Build and push dev
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./seo_link_recommender/backend
          file: ./seo_link_recommender/backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:dev
      - name: Read version from README
        if: github.ref == 'refs/heads/main'
        id: version
        run: echo "version=$(grep '^Версия:' README.md | awk '{print $2}')" >> $GITHUB_OUTPUT
      - name: Tag commit
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag "v${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}"
