name: CI

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f relink/backend/requirements.txt ]; then pip install -r relink/backend/requirements.txt; fi
      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: ./relink
          file: ./relink/backend/Dockerfile
          push: false

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f relink/backend/requirements.txt ]; then pip install -r relink/backend/requirements.txt; fi
      - name: Run tests
        run: python -m pytest -q

